#!/bin/bash
# inactive_color=0x002c2e34
# background_color=0x002c2e34
options=(
    style=round
    width=8.0
    hidpi=off
    active_color=0xffFFFFFF
    inactive_color=0xff89B4FA
    background_color=0x901E1E2E
)

borders "${options[@]}"
